### ISSUE TITLE
Error using Gradle 5.6.1

### ISSUE THREAD

**Issue by jvs64893** [boothen/gradle-wsimport#7]
When using Gradle 5.6.1 I get an error when using the wsimport task. The same task works flawlessly in Gradle 5.5.1.

Stacktrace:
```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.sun.tools.ws.resources.WscompileMessages
        at com.sun.tools.ws.wscompile.WsimportTool$1AuthListener.onError(WsimportTool.java:377)
        at com.sun.istack.tools.DefaultAuthenticator.setAuth(DefaultAuthenticator.java:138)
        at com.sun.tools.ws.wscompile.WsimportTool.buildWsdlModel(WsimportTool.java:400)
        at com.sun.tools.ws.wscompile.WsimportTool.run(WsimportTool.java:175)
        at com.sun.tools.ws.wscompile.WsimportTool.run(WsimportTool.java:153)
        at com.sun.tools.ws.ant.WsImportBase.runInVm(WsImportBase.java:569)
        at com.sun.tools.ws.ant.WsTask2.execute(WsTask2.java:457)
        at com.sun.tools.ws.ant.WsImportBase.execute(WsImportBase.java:552)
        at com.sun.tools.ws.ant.WsImport.execute(WsImport.java:81)
        at com.sun.tools.ws.ant.WsImport2.execute(WsImport2.java:23)
        at uk.co.boothen.gradle.wsimport.WsImportRunnable.run(WsImportRunnable.java:73)
        at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:50)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:47)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:65)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:61)
        at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.execute(NoIsolationWorkerFactory.java:61)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
        at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
        at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:56)
        at org.gradle.workers.internal.DefaultWorkerExecutor$3.call(DefaultWorkerExecutor.java:215)
        at org.gradle.workers.internal.DefaultWorkerExecutor$3.call(DefaultWorkerExecutor.java:210)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
        at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
        ... 3 more
```

**Comment by boothen** [comment]
Hi there,

Sorry about this. I've just tried with 5.6.1 and can't reproduce the error. 

Are you using version 0.9 of the plugin? 
What JDK are you using? 
Is it possible you could share the gradle configuration you've set for the wsimport task?

Cheers,
Matt.

**Comment by Rouche** [comment]
Same error here with 5.6.2
Using JHipster generator project 6.3.1
Running on Windows with Adopt JDK 11
Notable Config lines:
```
    classpath "uk.co.boothen.gradle.wsimport:uk.co.boothen.gradle.wsimport.gradle.plugin:0.10"
apply plugin: "uk.co.boothen.gradle.wsimport"
...
sourceCompatibility=11
targetCompatibility=11
...
task wsimport(type: uk.co.boothen.gradle.wsimport.WsImport) {
    wsdlSourceRoot = "src/main/resources/schema/wsdl"
    generatedSourceRoot = "generated/java/main"
    generatedClassesRoot = "classes/java/main"

    keep = true
    extension = true
    verbose = true
    quiet = true
    debug = true
    xnocompile = true

    wsdl("/xxxx.wsdl") {
        bindingFile ("jaxb-bindings.xml")
        xjcarg("-XautoNameResolution")
        extraArg("-XadditionalHeaders")
        setWsdlLocation ("/schema/wsdl/xxxx.wsdl")
    }
}

```

Error:
Seems something is weird hapenning with `com.sun.istack.tools.DefaultAuthenticator.setAuth`
```
* What went wrong:
Execution failed for task ':wsimport'.
> A failure occurred while executing Importing WSDL
   > Could not initialize class com.sun.tools.ws.resources.WscompileMessages

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':wsimport'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:166)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:163)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:156)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
	at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
	at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: org.gradle.workers.internal.DefaultWorkerExecutor$WorkExecutionException: A failure occurred while executing Importing WSDL
	at org.gradle.workers.internal.DefaultWorkerExecutor$WorkItemExecution.waitForCompletion(DefaultWorkerExecutor.java:375)
	at org.gradle.internal.work.DefaultAsyncWorkTracker.waitForItemsAndGatherFailures(DefaultAsyncWorkTracker.java:142)
	at org.gradle.internal.work.DefaultAsyncWorkTracker.waitForItemsAndGatherFailures(DefaultAsyncWorkTracker.java:94)
	at org.gradle.internal.work.DefaultAsyncWorkTracker.waitForAll(DefaultAsyncWorkTracker.java:80)
	at org.gradle.internal.work.DefaultAsyncWorkTracker.waitForCompletion(DefaultAsyncWorkTracker.java:68)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:484)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:461)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:444)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:93)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:237)
	at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
	at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
	at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)
	at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
	at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
	at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
	at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)
	at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
	at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:208)
	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)
	at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
	at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
	at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)
	at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
	at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
	at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:69)
	at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:47)
	at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:140)
	... 34 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.sun.tools.ws.resources.WscompileMessages
	at com.sun.tools.ws.wscompile.WsimportTool$1AuthListener.onError(WsimportTool.java:377)
	at com.sun.istack.tools.DefaultAuthenticator.setAuth(DefaultAuthenticator.java:138)
	at com.sun.tools.ws.wscompile.WsimportTool.buildWsdlModel(WsimportTool.java:400)
	at com.sun.tools.ws.wscompile.WsimportTool.run(WsimportTool.java:175)
	at com.sun.tools.ws.wscompile.WsimportTool.run(WsimportTool.java:153)
	at com.sun.tools.ws.ant.WsImportBase.runInVm(WsImportBase.java:569)
	at com.sun.tools.ws.ant.WsTask2.execute(WsTask2.java:457)
	at com.sun.tools.ws.ant.WsImportBase.execute(WsImportBase.java:552)
	at com.sun.tools.ws.ant.WsImport.execute(WsImport.java:81)
	at com.sun.tools.ws.ant.WsImport2.execute(WsImport2.java:23)
	at uk.co.boothen.gradle.wsimport.WsImportRunnable.run(WsImportRunnable.java:73)
	at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:50)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:47)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:65)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:61)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.execute(NoIsolationWorkerFactory.java:61)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:56)
	at org.gradle.workers.internal.DefaultWorkerExecutor$3.call(DefaultWorkerExecutor.java:215)
	at org.gradle.workers.internal.DefaultWorkerExecutor$3.call(DefaultWorkerExecutor.java:210)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
	... 3 more
```

**Comment by Rouche** [comment]
If i add this dependency `classpath "com.sun.xml.ws:jaxws-tools:2.3.2"`

I get:
```
Caused by: java.lang.NoSuchMethodError: 'void com.sun.istack.localization.LocalizableMessageFactory.<init>(java.lang.String, com.sun.istack.localization.LocalizableMessageFactory$ResourceBundleSupplier)'
	at com.sun.tools.ws.resources.WscompileMessages.<clinit>(WscompileMessages.java:28)
	at com.sun.tools.ws.wscompile.WsimportTool$1AuthListener.onError(WsimportTool.java:377)
	at com.sun.istack.tools.DefaultAuthenticator.setAuth(DefaultAuthenticator.java:138)
	at com.sun.tools.ws.wscompile.WsimportTool.buildWsdlModel(WsimportTool.java:400)
	at com.sun.tools.ws.wscompile.WsimportTool.run(WsimportTool.java:175)
	at com.sun.tools.ws.wscompile.WsimportTool.run(WsimportTool.java:153)
	at com.sun.tools.ws.ant.WsImportBase.runInVm(WsImportBase.java:569)
	at com.sun.tools.ws.ant.WsTask2.execute(WsTask2.java:457)
	at com.sun.tools.ws.ant.WsImportBase.execute(WsImportBase.java:552)
	at com.sun.tools.ws.ant.WsImport.execute(WsImport.java:81)
	at com.sun.tools.ws.ant.WsImport2.execute(WsImport2.java:23)
	at uk.co.boothen.gradle.wsimport.WsImportRunnable.run(WsImportRunnable.java:73)
	at org.gradle.workers.internal.AdapterWorkAction.execute(AdapterWorkAction.java:50)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:47)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:65)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1$1.create(NoIsolationWorkerFactory.java:61)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:98)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1$1.execute(NoIsolationWorkerFactory.java:61)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:44)
	at org.gradle.workers.internal.AbstractWorker$1.call(AbstractWorker.java:41)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
	at org.gradle.workers.internal.AbstractWorker.executeWrappedInBuildOperation(AbstractWorker.java:41)
	at org.gradle.workers.internal.NoIsolationWorkerFactory$1.execute(NoIsolationWorkerFactory.java:56)
	at org.gradle.workers.internal.DefaultWorkerExecutor$3.call(DefaultWorkerExecutor.java:215)
	at org.gradle.workers.internal.DefaultWorkerExecutor$3.call(DefaultWorkerExecutor.java:210)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runExecution(DefaultConditionalExecutionQueue.java:215)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.runBatch(DefaultConditionalExecutionQueue.java:164)
	at org.gradle.internal.work.DefaultConditionalExecutionQueue$ExecutionRunner.run(DefaultConditionalExecutionQueue.java:131)
```

**Comment by Rouche** [comment]
Error seems to be coming from com.sun.istack:istack-commons-tools:3.0.8
Adding `extraArg("-XadditionalHeaders -XdisableAuthenticator")`
I get futher but no success
```
Caused by: java.lang.NoSuchMethodError: 'void com.sun.istack.localization.LocalizableMessageFactory.<init>(java.lang.String, com.sun.istack.localization.LocalizableMessageFactory$ResourceBundleSupplier)'
	at com.sun.tools.ws.resources.WscompileMessages.<clinit>(WscompileMessages.java:28)
	at com.sun.tools.ws.wscompile.WsimportOptions.parseArguments(WsimportOptions.java:234)
	at com.sun.tools.ws.wscompile.WsimportTool.parseArguments(WsimportTool.java:349)
	at com.sun.tools.ws.wscompile.WsimportTool.run(WsimportTool.java:172)
	at com.sun.tools.ws.wscompile.WsimportTool.run(WsimportTool.java:153)
	at com.sun.tools.ws.ant.WsImportBase.runInVm(WsImportBase.java:569)
	at com.sun.tools.ws.ant.WsTask2.execute(WsTask2.java:457)
	at com.sun.tools.ws.ant.WsImportBase.execute(WsImportBase.java:552)
	at com.sun.tools.ws.ant.WsImport.execute(WsImport.java:81)
	at com.sun.tools.ws.ant.WsImport2.execute(WsImport2.java:23)
	at uk.co.boothen.gradle.wsimport.WsImportRunnable.run(WsImportRunnable.java:73)
```

**Comment by boothen** [comment]
Hi @Rouche,
Thanks for this. I'll take a look and come back to you with a fix.

Cheers.

**Comment by boothen** [comment]
Hi @Rouche,

Something doesn't seem quite right. I don't think you need to add jaxws-tools to the classpath. The NoSuchMethodError would be from an earlier version of LocalizableMessageFactory being found on the classpath.

Are you defining the plugin? Using

```
plugins {
  id "uk.co.boothen.gradle.wsimport" version "0.10"
}
```

or the old style of

```
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "gradle.plugin.uk.co.boothen.gradle:gradle-wsimport:0.10"
  }
}
```

I'm not sure what you mean by using:
`classpath "uk.co.boothen.gradle.wsimport:uk.co.boothen.gradle.wsimport.gradle.plugin:0.10"`

**Comment by Rouche** [comment]
Sorry i just did not want to put too much source. It is my buildscript part.
```
buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()
        jcenter()
        maven { url "http://repo.spring.io/plugins-release" }
    }
    dependencies {
        ......
        classpath "uk.co.boothen.gradle.wsimport:uk.co.boothen.gradle.wsimport.gradle.plugin:0.10"
        classpath "org.unbroken-dome.xjc:org.unbroken-dome.xjc.gradle.plugin:1.4.3"
        //jhipster-needle-gradle-buildscript-dependency - JHipster will add additional gradle build script plugins here
    }
}
```

**Comment by boothen** [comment]
No problem. I'm wondering if the XJC Plugin is conflicting with this plugin. The XJC Plugin has a dependency on jaxb-core:2.2.1.1 this contains an earlier version of LocalizableMessageFactory.

I've published a temporary fix plugin 0.11-FIX to the Gradle plugin repository. Could you give that a try? 

If that fails is it possible to run your build without the XJC Plugin configured? To verify if it is the duplicate LocalizableMessageFactory issue.

Thanks.

**Comment by Rouche** [comment]
Previous version of JHipster / Gradle had the same dependencies. It was working well.
0.11-FIX have same problem.

This is just crazy, removing unbroken-dome.xjc the wsimport task works.

This is even more crazy because removing unbroken-dome makes the option `-XdisableAuthenticator` invalid. There is definatelly a different implementation of the class between both plugins.

Gradle 5.6.x might have a classpath resolution order different from 5.4 / 5.5, this is the only explanation i can think of.

Now how i will be able to fix this :/

**Comment by Rouche** [comment]
Problem solved, we need to force dependency `com.sun.istack:istack-commons-runtime` to 3.0.8+
I'm really sorry if you lost too much time on this.
@jvs64893 you can try this.
```
buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()
        maven { url "https://repo.spring.io/plugins-release" }
    }
    dependencies {
        classpath "com.sun.istack:istack-commons-runtime:3.0.9"
        ......
        classpath "uk.co.boothen.gradle.wsimport:uk.co.boothen.gradle.wsimport.gradle.plugin:0.10"
        classpath "org.unbroken-dome.xjc:org.unbroken-dome.xjc.gradle.plugin:1.4.3"
        //jhipster-needle-gradle-buildscript-dependency - JHipster will add additional gradle build script plugins here
    }
}
```

**Comment by boothen** [comment]
Interesting. Strange that it worked in earlier Gradle versions. Good to know though so thanks for coming back with the details.

Does JHipster require you to use the old style buildscript convention to define plugins? I wonder if you'll see the issue if you use new convention?

```
plugins {
    id "uk.co.boothen.gradle.wsimport" version "0.10"
    id "org.unbroken-dome.xjc" version "1.4.3"
}
```

**Comment by Rouche** [comment]
Not necessarily, but i think we have an issue with new convention because of nexus firewall. I did not ask too much questions :)

**Comment by boothen** [comment]
Have you defined the plugin management repository in `settings.gradle`? You'll need something like this:

```
pluginManagement {
    repositories {
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()
        maven { url "https://repo.spring.io/plugins-release" }
    }
}
```

However, changing the plugin definition might be a red herring. I've been looking into this further and it seems there was a change in Gradle 5.6 around how plugins can define their isolation from other plugins. The change involves a bit of rework so won't be able to get a fix out too soon. I'll let you know when I do. At least you can use your workaround for now.

**Comment by boothen** [comment]
I've made the changes to the plugin could you try with version 0.11? This should use a separate classloader when the plugin runs.

**Comment by Rouche** [comment]
It works! Really nice!

**Comment by boothen** [comment]
Great!! :)

As an a side I noticed you were having to use setWdslLocation. I think that slipped through a code review. You can now use wsdlLocation as well.
